### ISSUE TITLE
fix: Invalid plugin options for "@imgix/gatsby" - "domain" is required

### ISSUE THREAD

**Issue by arsinclair** [imgix/gatsby#254]
We're upgrading from v2.0.3 to v2.0.4 of this library and we started receiving such error on `gatsby develop`:

> success load gatsby config - 0.088s
 ERROR #11331  PLUGIN
Invalid plugin options for "@imgix/gatsby":
> - "domain" is required

The release notes for v2.0.4 doesn't list any changes in the way how the _domain_ setting logic is handled, which makes us think that this is a bug.

This is the configuration we use:

```js
{
    resolve: "@imgix/gatsby",
    options: {
        domain: "", // keep it empty, since we want to preserve domain name together with the link
        sourceType: ImgixSourceType.AmazonS3,
        fields: [
            {
                nodeType: "ImagesJson",
                rawURLKey: "url",
                fieldName: "image"
            }
        ],
        disableIxlibParam: true
    }
}
```

We intentionally set _domain_ to be empty because we want to keep the full URL of our imgix images in our components.

The README.md states:

> If url is: an imgix URL, domain and secureURLToken are likely not required. If domain is set, the source must be a Web Proxy Source. If "secure URLs" are enabled on the imgix source, or the source is a Web Proxy Source, secureURLToken is required.

We tried removing the domain parameter from the config entirely as the docs suggest that it's optional, but we receive the same error.

What can be done about this? Thank you in advance!

**Comment by luqven** [comment]
Hey @arsinclair, thanks for opening this issue.

This does seem like a bug, `domain` should have remained optional. I can't give you a time estimate yet, but we'll investigate and update this ticket.

**Comment by arsinclair** [comment]
Hi, has there been any progress with this issue? It prevents us from upgrading the plugin further and it also prevents us from migrating to Gatsby v5.

**Comment by luqven** [comment]
Hey @arsinclair , my apols for the delay here.

We ran into a blocker with our E2E tests, the setup there isn't ideal and needs to be fixed. That held this fix back longer than it probably should have.

#261 should have addressed this issue. 

This issue was caused by our refactoring away from FPTS and to Joi schemas. We inadvertently set `domain` as `required` when this refactoring took place. You will now be able to entirely omit the `domain` field rather than having to set it to an empty string.
```js
{
    resolve: "@imgix/gatsby",
    options: {
        // don't set `domain` at all, if you use absolute URLs you won't need it
        sourceType: ImgixSourceType.AmazonS3,
        fields: [
            {
                nodeType: "ImagesJson",
                rawURLKey: "url",
                fieldName: "image"
            }
        ],
        disableIxlibParam: true
    }
}
```

You can try this out on `@imgix/gatsby@next` or this [CodeSandbox](https://codesandbox.io/p/github/imgix/gatsby/l/codesandbox?selection=%5B%7B%22endColumn%22%3A16%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A16%2C%22startLineNumber%22%3A6%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cldpo1kjo00369ig38gnrfhbn%2522%252C%2522openFiles%2522%253A%255B%2522%252Ftest%252Fdev-and-e2e%252Fgatsby-config.js%2522%252C%2522%252Ftest%252Fdev-and-e2e%252Fpackage.json%2522%255D%252C%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cldpo1mk702ll3b6ie4iaande%2522%253A%257B%2522key%2522%253A%2522cldpo1mk702ll3b6ie4iaande%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%253Astart%2522%252C%2522port%2522%253A8000%252C%2522key%2522%253A%2522cldpof6cx00tx3b6izzm730hc%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%253Astart%2522%252C%2522key%2522%253A%2522cldpoeeh600bk3b6i09ra6bah%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cldpo1mk702ll3b6ie4iaande%2522%252C%2522spacesOrder%2522%253A%255B%2522cldpo1mk702ll3b6ie4iaande%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D). Note, the sandbox serves an example app from `test/dev-and-e2e`.

Please do let us know if this doesn't address the problem and we'll be happy to look into it. We plan to cut a release with this fix soon.

**Comment by arsinclair** [comment]
Thanks @luqven, I just tested `@imgix/gatsby@next` and it works fine!
